import { menuIcons } from "./menuIcons";

export const commonMenu = [
    {
      label: "Обзор",
      to: "/crm/obzor",
      icon: menuIcons.clipboard,
      permission: "can_view_dashboard",
      implemented: true,
    },
    {
      label: "Закупки",
      to: "/crm/zakaz",
      icon: menuIcons.listAlt,
      permission: "can_view_orders",
      implemented: true,
    },
    {
      label: "Продажа",
      to: "/crm/sell",
      icon: menuIcons.scale,
      permission: "can_view_sale",
      implemented: true,
    },
    {
      label: "Аналитика",
      to: "/crm/analytics",
      icon: menuIcons.chartBar,
      permission: "can_view_analytics",
      implemented: true,
    },
    {
      label: "Склад",
      to: "/crm/sklad",
      icon: menuIcons.warehouse,
      permission: "can_view_products",
      implemented: true,
    },
    {
      label: "Касса",
      to: "/crm/kassa",
      icon: menuIcons.landmark,
      permission: "can_view_cashbox",
      implemented: true,
    },
    {
      label: "Сотрудники",
      to: "/crm/employ",
      icon: menuIcons.user,
      permission: "can_view_employees",
      implemented: true,
    },
    {
      label: "Бронирование",
      to: "/crm/raspisanie",
      icon: menuIcons.calendar,
      permission: "can_view_booking",
      implemented: true,
    },
    {
      label: "Клиенты",
      to: "/crm/clients",
      icon: menuIcons.filePerson,
      permission: "can_view_clients",
      implemented: true,
    },
    {
      label: "Филиалы",
      to: "/crm/branch",
      icon: menuIcons.store,
      permission: "can_view_branch",
      implemented: true,
    },
    {
      label: "Отделы",
      to: "/crm/departments",
      icon: menuIcons.users,
      permission: "can_view_departments",
      implemented: true,
    },
    {
      label: "Долги",
      to: "/crm/debts",
      icon: menuIcons.users,
      permission: "can_view_debts",
      implemented: true,
    },
    {
      label: "Бренд,Категория",
      to: "/crm/brand-category",
      icon: menuIcons.instagram,
      permission: "can_view_brand_category",
      implemented: true,
    },
    {
      label: "Настройки",
      to: "/crm/set",
      icon: menuIcons.cog,
      permission: "can_view_settings",
      implemented: true,
    },
  ];
