import { menuIcons } from "../menuIcons";

export const additionalMenu = [
    {
      id: "whatsapp",
      label: "WhatsApp",
      to: "/crm/",
      icon: menuIcons.comments,
      permission: "can_view_whatsapp",
      permissionModel: "company",
      implemented: true,
    },
    {
      id: "instagram",
      label: "Instagram",
      to: "/crm/instagram",
      icon: menuIcons.instagramIcon,
      permission: "can_view_instagram",
      permissionModel: "company",
      implemented: true,
    },
    {
      id: "telegram",
      label: "Telegram",
      to: "/crm/",
      icon: menuIcons.comments,
      permission: "can_view_telegram",
      permissionModel: "company",
      implemented: true,
    },
    {
      id: "documents",
      label: "Документы",
      to: "/crm/documents",
      icon: menuIcons.documentScanner,
      permission: "can_view_documents",
      permissionModel: "company",
      implemented: true,
    },
    {
      id: "barcode-print",
      label: "Печать штрих-кодов",
      to: "/crm/barcodes",
      icon: menuIcons.documentScanner,
      permission: "can_view_market_label",
      permissionModel: "user",
      implemented: true,
    },
    {
      id: "scales",
      label: "Интеграция с весами",
      to: "/crm/scales",
      icon: menuIcons.scale,
      permission: "can_view_market_scales",
      permissionModel: "user",
      implemented: true,
    },
  ];
