import { menuIcons } from "../menuIcons";

export const barberSectorMenus = {
    barber: [
      {
        label: "Аналитика",
        to: "/crm/barber/cash-reports",
        icon: menuIcons.chartBar,
        permission: "can_view_cashbox",
        implemented: true,
      },
      {
        label: "Клиенты",
        to: "/crm/barber/clients",
        icon: menuIcons.filePerson,
        permission: "can_view_barber_clients",
        implemented: true,
      },
      {
        label: "Документы клиентов",
        to: "/crm/barber/client-documents",
        icon: menuIcons.fileText,
        permission: "can_view_document",
        implemented: true,
      },
      {
        label: "Услуги",
        to: "/crm/barber/services",
        icon: menuIcons.tags,
        permission: "can_view_barber_services",
        implemented: true,
      },
      {
        label: "История",
        to: "/crm/barber/history",
        icon: menuIcons.clipboard,
        permission: "can_view_barber_history",
        implemented: true,
      },
      {
        label: "Записи",
        to: "/crm/barber/records",
        icon: menuIcons.calendar,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Заявки",
        to: "/crm/barber/requests",
        icon: menuIcons.clipboardList,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Сотрудники",
        to: "/crm/barber/masters",
        icon: menuIcons.user,
        permission: "can_view_employees",
        implemented: true,
      },
      {
        label: "Зарплата",
        to: "/crm/barber/salary",
        icon: menuIcons.wallet,
        permission: "can_view_salary",
        implemented: true,
      },
      //       {
      //   label: "Склад",
      //   to: "/crm/barber/warehouse",
      //   icon: menuIcons.warehouse,
      //   permission: "can_view_products",
      //   implemented: true,
      // },
    ],
    services: [
      {
        label: "Аналитика",
        to: "/crm/services/cash-reports",
        icon: menuIcons.chartBar,
        permission: "can_view_cashbox",
        implemented: true,
      },
      {
        label: "Клиенты",
        to: "/crm/services/clients",
        icon: menuIcons.filePerson,
        permission: "can_view_barber_clients",
        implemented: true,
      },
      {
        label: "Документы клиентов",
        to: "/crm/services/client-documents",
        icon: menuIcons.fileText,
        permission: "can_view_document",
        implemented: true,
      },
      {
        label: "Услуги",
        to: "/crm/services/services",
        icon: menuIcons.tags,
        permission: "can_view_barber_services",
        implemented: true,
      },
      {
        label: "История",
        to: "/crm/services/history",
        icon: menuIcons.clipboard,
        permission: "can_view_barber_history",
        implemented: true,
      },
      {
        label: "Записи",
        to: "/crm/services/records",
        icon: menuIcons.calendar,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Заявки",
        to: "/crm/services/requests",
        icon: menuIcons.clipboardList,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Сотрудники",
        to: "/crm/services/masters",
        icon: menuIcons.user,
        permission: "can_view_employees",
        implemented: true,
      },
      {
        label: "Зарплата",
        to: "/crm/services/salary",
        icon: menuIcons.wallet,
        permission: "can_view_salary",
        implemented: true,
      },
    ],
    dentistry: [
      {
        label: "Аналитика",
        to: "/crm/dentistry/cash-reports",
        icon: menuIcons.chartBar,
        permission: "can_view_cashbox",
        implemented: true,
      },
      {
        label: "Клиенты",
        to: "/crm/dentistry/clients",
        icon: menuIcons.filePerson,
        permission: "can_view_barber_clients",
        implemented: true,
      },
      {
        label: "Документы клиентов",
        to: "/crm/dentistry/client-documents",
        icon: menuIcons.fileText,
        permission: "can_view_document",
        implemented: true,
      },
      {
        label: "Услуги",
        to: "/crm/dentistry/services",
        icon: menuIcons.tags,
        permission: "can_view_barber_services",
        implemented: true,
      },
      {
        label: "История",
        to: "/crm/dentistry/history",
        icon: menuIcons.clipboard,
        permission: "can_view_barber_history",
        implemented: true,
      },
      {
        label: "Записи",
        to: "/crm/dentistry/records",
        icon: menuIcons.calendar,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Заявки",
        to: "/crm/dentistry/requests",
        icon: menuIcons.clipboardList,
        permission: "can_view_barber_records",
        implemented: true,
      },
      {
        label: "Сотрудники",
        to: "/crm/dentistry/masters",
        icon: menuIcons.user,
        permission: "can_view_employees",
        implemented: true,
      },
      {
        label: "Зарплата",
        to: "/crm/dentistry/salary",
        icon: menuIcons.wallet,
        permission: "can_view_salary",
        implemented: true,
      },
    ],
};
