import { menuIcons } from "../menuIcons";

export const buildingMenu = [
      {
        label: "Аналитика",
        to: "/crm/building/analytics",
        icon: menuIcons.chartBar,
        permission: "can_view_building_analytics",
        implemented: true,
      },
      {
        label: "Касса",
        to: "/crm/building/cash-register",
        icon: menuIcons.cashRegister,
        permission: "can_view_building_cash_register",
        implemented: true,
      },
      {
        label: "Клиенты",
        to: "/crm/building/clients",
        icon: menuIcons.filePerson,
        permission: "can_view_building_clients",
        implemented: true,
      },
      {
        label: "Сотрудники",
        to: "/crm/building/employees",
        icon: menuIcons.user,
        permission: "can_view_employees",
        implemented: true,
      },
      {
        label: "Напоминания",
        to: "/crm/building/notification",
        icon: menuIcons.bell,
        permission: "can_view_building_notification",
        implemented: true,
      },
      {
        label: "Закупки",
        to: "/crm/building/procurement",
        icon: menuIcons.cart,
        permission: "can_view_building_procurement",
        implemented: true,
      },
      {
        label: "ЖК",
        to: "/crm/building/projects",
        icon: menuIcons.listCheck,
        permission: "can_view_building_projects",
        implemented: true,
      },
      {
        label: "Проекты",
        to: "/crm/building/drawings",
        icon: menuIcons.fileText,
        permission: "can_view_building_treaty",
        implemented: true,
      },
      {
        label: "Зарплата",
        to: "/crm/building/salary",
        icon: menuIcons.money,
        permission: "can_view_building_salary",
        implemented: true,
      },
      {
        label: "Продажи",
        to: "/crm/building/sell",
        icon: menuIcons.tags,
        permission: "can_view_building_sell",
        implemented: true,
      },
      {
        label: "Склад",
        to: "/crm/building/stock",
        icon: menuIcons.box,
        permission: "can_view_building_stock",
        implemented: true,
      },
      {
        label: "Договора",
        to: "/crm/building/treaty",
        icon: menuIcons.fileText,
        permission: "can_view_building_treaty",
        implemented: true,
      },
      {
        label: "Строительные отделы",
        to: "/crm/building/work",
        icon: menuIcons.clipboard,
        permission: "can_view_building_work_process",
        implemented: true,
      },
    ];
