import { menuIcons } from "../menuIcons";

export const cafeMenu = [
      {
        label: "Аналитика",
        to: "/crm/cafe/analytics",
        icon: menuIcons.barChart3,
        permission: "can_view_analytics",
        implemented: true,
      },
      {
        label: "Меню",
        to: "/crm/cafe/menu",
        icon: menuIcons.bookOpenText,
        permission: "can_view_cafe_menu",
        implemented: true,
      },
      {
        label: "Заказы",
        to: "/crm/cafe/orders",
        icon: menuIcons.receiptText,
        permission: "can_view_cafe_orders",
        implemented: true,
      },
      {
        label: "Кухня",
        to: "/crm/cafe/cook",
        icon: menuIcons.chefHat,
        permission: "can_view_cafe_cook",
        implemented: true,
      },
      {
        label: "Зарплата",
        to: "/crm/cafe/payroll",
        icon: menuIcons.badgeDollarSign,
        permission: "can_view_employees",
        implemented: true,
      },
      {
        label: "Закупки",
        to: "/crm/cafe/purchasing",
        icon: menuIcons.shoppingCart,
        permission: "can_view_cafe_purchasing",
        implemented: true,
      },
      {
        label: "Отчёты",
        to: "/crm/cafe/reports",
        icon: menuIcons.fileBarChart,
        permission: "can_view_analytics",
        implemented: true,
      },
      {
        label: "Бронь",
        to: "/crm/cafe/reservations",
        icon: menuIcons.calendarCheck2,
        permission: "can_view_cafe_booking",
        implemented: true,
      },
      {
        label: "Гости",
        to: "/crm/cafe/clients",
        icon: menuIcons.users,
        permission: "can_view_cafe_clients",
        implemented: true,
      },
      {
        label: "Склад",
        to: "/crm/cafe/stock",
        icon: menuIcons.boxes,
        permission: "can_view_products",
        implemented: true,
      },
      {
        label: "Заготовки",
        to: "/crm/cafe/costing",
        icon: menuIcons.scale,
        permission: "can_view_cafe_calculation",
        implemented: true,
      },
      {
        label: "Инвентаризация",
        to: "/crm/cafe/inventory",
        icon: menuIcons.clipboardCheck,
        permission: "can_view_cafe_inventory",
        implemented: true,
      },
      {
        label: "Столы",
        to: "/crm/cafe/tables",
        icon: menuIcons.table2,
        permission: "can_view_cafe_tables",
        implemented: true,
      },
      {
        label: "Касса",
        to: "/crm/cafe/kassa",
        icon: menuIcons.wallet,
        permission: "can_view_cashbox",
        implemented: true,
      },
    ];
