export {
  listFrom,
  toDecimalString,
  kindLabel,
  ruStatusToKind,
  kindToRu,
  typeLabel,
  todayISO,
  getInstallmentRemaining,
  getInstallmentStatus,
  dealHasPayments,
  resolveDebtFromDeals,
  normalizeDealFromApi,
  buildDealPayload,
  normalizeDealCreateInput,
  msgFromError,
  toIsoDate10,
  toYYYYMMDD,
  formatDateDDMMYYYY,
  toNumber,
} from "../../../../tools/clientDeals";
