import { Route } from "react-router-dom";
import BuildingLayout, {
  BuildingAnalytics,
  BuildingCashRegister,
  BuildingCashRegisterTreatyDetail,
  BuildingCashRegisterSalaryPayrollPaymentsPage,
  BuildingClients,
  SupplierCreatePage,
  SupplierDetailPage,
  ContractorCreatePage,
  ContractorDetailPage,
  BuildingClientDetail,
  BuildingNotification,
  BuildingTaskDetail,
  BuildingProcurement,
  BuildingProjects,
  BuildingProjectDetail,
  BuildingSalary,
  BuildingSalaryEmployeeDetail,
  BuildingSalaryPayrollDetail,
  BuildingSalaryLineDetail,
  BuildingSell,
  BuildingStock,
  BuildingTreaty,
  BuildingTreatyDetail,
  BuildingProcurementDetail,
  BuildingStockDetail,
  BuildingStockTransferDetail,
  BuildingWorkProcess,
  BuildingWorkProcessDetail,
  BuildingDrawings,
  BuildingEmployees,
} from "@/Components/pages/Building";
import { createProtectedRoute } from "./helpers";

export const buildingRoutes = () => [
  <Route key="building" element={<BuildingLayout />} path="building">
    {[
      createProtectedRoute("analytics", BuildingAnalytics),
      createProtectedRoute("cash-register", BuildingCashRegister),
      createProtectedRoute(
        "cash-register/treaty/:treatyId",
        BuildingCashRegisterTreatyDetail,
      ),
      createProtectedRoute(
        "cash-register/salary-payroll/:payrollId",
        BuildingCashRegisterSalaryPayrollPaymentsPage,
      ),
      createProtectedRoute("clients", BuildingClients),
      createProtectedRoute("clients/:id", BuildingClientDetail),
      createProtectedRoute("clients/suppliers/new", SupplierCreatePage),
      createProtectedRoute("clients/suppliers/:id", SupplierDetailPage),
      createProtectedRoute("clients/contractors/new", ContractorCreatePage),
      createProtectedRoute("clients/contractors/:id", ContractorDetailPage),
      createProtectedRoute("employees", BuildingEmployees),
      createProtectedRoute("notification", BuildingNotification),
      createProtectedRoute("notification/new", BuildingTaskDetail),
      createProtectedRoute("notification/:id", BuildingTaskDetail),
      createProtectedRoute("work", BuildingWorkProcess),
      createProtectedRoute("work/:id", BuildingWorkProcessDetail),
      createProtectedRoute("procurement", BuildingProcurement),
      createProtectedRoute("procurement/:id", BuildingProcurementDetail),
      createProtectedRoute("projects", BuildingProjects),
      createProtectedRoute("projects/:id", BuildingProjectDetail),
      createProtectedRoute("drawings", BuildingDrawings),
      createProtectedRoute("salary", BuildingSalary),
      createProtectedRoute("salary/employee/:id", BuildingSalaryEmployeeDetail),
      createProtectedRoute("salary/payroll/:id", BuildingSalaryPayrollDetail),
      createProtectedRoute(
        "salary/payroll/:payrollId/line/:lineId",
        BuildingSalaryLineDetail,
      ),
      createProtectedRoute("sell", BuildingSell),
      createProtectedRoute("stock", BuildingStock),
      createProtectedRoute("stock/:id", BuildingStockDetail),
      createProtectedRoute(
        "stock/:warehouseId/transfer/:id",
        BuildingStockTransferDetail,
      ),
      createProtectedRoute("treaty", BuildingTreaty),
      createProtectedRoute("treaty/new", BuildingTreatyDetail),
      createProtectedRoute("treaty/:id", BuildingTreatyDetail),
    ]}
  </Route>,
];
